name: Common Validate

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  markdown-lint:
    uses: ./.github/workflows/markdown-lint.yml
    with:
      working-directory: ${{ inputs.working-directory }}

  docker-lint:
    uses: ./.github/workflows/docker-lint.yml
    with:
      working-directory: ${{ inputs.working-directory }}
