name: Container Validate

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  common-lint:
    uses: ./.github/workflows/common-lint.yml
    with:
      working-directory: ${{ inputs.working-directory }}

  node-common-lint:
    uses: ./.github/workflows/node-common-lint.yml
    with:
      package-manager: npm
      working-directory: ${{ inputs.working-directory }}

  node-test:
    uses: ./.github/workflows/node-test.yml
    with:
      package-manager: npm
      working-directory: ${{ inputs.working-directory }}
