name: Validate a dart project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      package-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  common-lint:
    uses: ./.github/workflows/common-lint.yml
    with:
      node-package-manager: none
      working-directory: ${{ inputs.package-dir }}

  dart-lint:
    uses: ./.github/workflows/dart-lint.yml
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
      package-dir: ${{ inputs.package-dir }}

  dart-test:
    uses: ./.github/workflows/dart-test.yml
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
      package-dir: ${{ inputs.package-dir }}
