name: Lint a dart project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      package-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  dart-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref }}

      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ inputs.package-dir }}

      - name: Verify build_runner generated files
        run: |
          if dart pub deps --executables | grep -q build_runner; then
            dart run build_runner build --delete-conflicting-outputs
          fi
          [ -z "$(git status -s)" ]
        working-directory: ${{ inputs.package-dir }}

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: ${{ inputs.package-dir }}

      - name: Analyse source code
        run: dart analyze --fatal-infos .
        working-directory: ${{ inputs.package-dir }}

      - name: Execute code_metrics
        run: |
          if dart pub deps --executables | grep -q ac_code_metrics; then
            dart run ac_code_metrics:metrics analyze .
          fi
        working-directory: ${{ inputs.package-dir }}
