name: Publish a dart lib project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      package-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  dart-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for requesting the JWT

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkout-ref }}

      - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1.7.0

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ inputs.package-dir }}

      - name: Publish (dry run)
        run: dart pub publish --dry-run
        working-directory: ${{ inputs.package-dir }}

      - name: Publish to pub.dev
        run: dart pub publish -f
        working-directory: ${{ inputs.package-dir }}
