name: Dart Lint

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  dart-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1.7.0

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ inputs.working-directory }}

      - name: Verify build_runner generated files
        run: |
          if dart pub deps --executables | grep -q build_runner; then
            dart run build_runner build --delete-conflicting-outputs
          fi
          [ -z "$(git status -s)" ]
        working-directory: ${{ inputs.working-directory }}

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: ${{ inputs.working-directory }}

      - name: Analyse source code
        run: dart analyze --fatal-infos .
        working-directory: ${{ inputs.working-directory }}

      - name: Execute code_metrics
        run: |
          if dart pub deps --executables | grep -q ac_code_metrics; then
            dart run ac_code_metrics:metrics analyze .
          fi
        working-directory: ${{ inputs.working-directory }}
