name: Flutter Validate

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  common-lint:
    uses: ./.github/workflows/common-lint.yml
    with:
      working-directory: ${{ inputs.working-directory }}

  flutter-lint:
    uses: ./.github/workflows/flutter-lint.yml
    with:
      working-directory: ${{ inputs.working-directory }}

  flutter-test:
    uses: ./.github/workflows/flutter-test.yml
    with:
      working-directory: ${{ inputs.working-directory }}
