name: Flutter Lib Publish

on:
  workflow_call:
    inputs:
      environment:
        description: Environment in which the workflow is required to run
        required: false
        type: string
      working-directory:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for requesting the JWT

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: flutter-actions/setup-flutter@03a3a60436d95e16d110127785240139a633ce70 #v4

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}

      - name: Publish (dry run)
        run: dart pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}

      - name: Publish to pub.dev
        # flutter pub publish does not work on CI (waits for auth)
        run: dart pub publish -f
        working-directory: ${{ inputs.working-directory }}
