name: Publish a flutter lib project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      package-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  flutter-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for requesting the JWT

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkout-ref }}

      # setup-dart action is required for setting up publish auth
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1

      - uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.package-dir }}

      - name: Publish (dry run)
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.package-dir }}

      - name: Publish to pub.dev
        run: flutter pub publish -f
        working-directory: ${{ inputs.package-dir }}
