name: Lint a Go project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      package-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  go-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.checkout-ref }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ${{ inputs.package-dir && format('{0}/go.mod', inputs.package-dir) || 'go.mod' }}
          cache: true

      - name: Verify formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Unformatted files:"
            echo "$unformatted"
            exit 1
          fi
        working-directory: ${{ inputs.package-dir }}

      - name: Analyse source code
        run: go vet ./...
        working-directory: ${{ inputs.package-dir }}
