name: Test a Go project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      package-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.checkout-ref }}

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ${{ inputs.package-dir && format('{0}/go.mod', inputs.package-dir) || 'go.mod' }}
          cache: true

      - name: Execute tests
        run: go test ./...
        working-directory: ${{ inputs.package-dir }}
