name: Markdown Lint

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory within the repository where the package is located."
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Lint Markdown files
        run: docker run -v $(pwd):/workdir davidanson/markdownlint-cli2 -- '**/*.md'
        working-directory: ${{ inputs.working-directory }}
