name: Node NPM Test

on:
  workflow_call:
    inputs:
      node-version:
        description: "Version Spec of the Node.js version to use (takes precedence over node-version-file). Examples: 12.x, 10.15.1, >=10.15.0."
        required: false
        type: string
      node-version-file:
        description: "File containing the version Spec of the version to use. Examples: package.json, .nvmrc, .node-version, .tool-versions."
        required: false
        type: string
        default: ".nvmrc"
      working-directory:
        description: "Directory within the repository where the package is located."
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}

      - name: Execute tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}
