name: Validate a Node.js project

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      working-dir:
        description: Directory within the repository where the package is located
        required: false
        type: string

jobs:
  common-lint:
    uses: ./.github/workflows/common-lint.yml
    with:
      node-package-manager: npm
      working-dir: ${{ inputs.working-dir }}

  node-common-lint:
    uses: ./.github/workflows/node-common-lint.yml
    with:
      node-package-manager: npm
      checkout-ref: ${{ inputs.checkout-ref }}
      package-dir: ${{ inputs.working-dir }}

  node-test:
    uses: ./.github/workflows/node-test.yml
    with:
      node-package-manager: npm
      checkout-ref: ${{ inputs.checkout-ref }}
      package-dir: ${{ inputs.working-dir }}
